In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.concat([pd.read_csv('scrapperv10_1_200.csv'),
                pd.read_csv('scrapperv10_201_400.csv'),
                pd.read_csv('scrapperv10_401_600.csv'),
                pd.read_csv('scrapperv10_601_800.csv'),
                pd.read_csv('scrapperv10_801_1000.csv'),
                pd.read_csv('scrapperv10_1001_1500.csv'),
                pd.read_csv('scrapperv10_1501_2000.csv')], ignore_index=True)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25504 entries, 0 to 25503
Data columns (total 7 columns):
Unnamed: 0           25504 non-null int64
actors               24598 non-null object
date                 25504 non-null object
movie                25504 non-null object
press_rating         9570 non-null float64
producer             25148 non-null object
spectators_rating    25177 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.4+ MB

In [5]:
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

,actors,date,movie,press_rating,producer,spectators_rating
0,Tye Sheridan ; Olivia Cooke ; Ben Mendelsohn ;,28 mars 2018,Ready Player One,4.2,Steven Spielberg ;,4.5
1,Franck Dubosc ; Alexandra Lamy ; Elsa Zylberst...,14 mars 2018,Tout le monde debout,3.6,Franck Dubosc ;,4.3
2,Rooney Mara ; Joaquin Phoenix ; Chiwetel Ejiof...,28 mars 2018,Marie Madeleine,2.2,Garth Davis ;,3.2
3,Arnaud Ducret ; Louise Bourgoin ; Timéo Bollan...,28 mars 2018,"Les dents, pipi et au lit",2.6,Emmanuel Gillibert ;,3.6
4,Cécile de France ;,28 mars 2018,Blue,3.6,Keith Scholey ; Alastair Fothergill ;,4.0

### Notes

Columns analysis:
- movie (= name) not relevant
- date ?
- output is press_rating or spectators_rating

To do:
- Missing values
- Actors and Producer columns transformation (one column by actor/producer with 0/1)

In [6]:
df.describe()

       press_rating  spectators_rating
count   9570.000000       25177.000000
mean       3.198966           3.065417
std        0.754706           0.557670
min        0.000000           0.900000
25%        2.700000           2.800000
50%        3.200000           3.100000
75%        3.700000           3.400000
max        5.000000           4.700000

In [7]:
df = pd.concat([df, df['actors'].str.get_dummies(sep=" ; ")], axis=1)

In [8]:
df.head()

,actors,date,movie,press_rating,producer,spectators_rating,'Rim'K' Brahmi-Benalla Abdelkrim,A. Martinez,A. Michael Baldwin,A.J.,...,İnanç Konukçu,İnci Pars,İnci Türkay,İsmail Hacıoğlu,Şafak Sezer,Şahan Gökbakar,Şahika Tekand,Şebnem Bozoklu,Şener Şen,Şükrü Özyıldız
0,Tye Sheridan ; Olivia Cooke ; Ben Mendelsohn ;,28 mars 2018,Ready Player One,4.2,Steven Spielberg ;,4.5,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Franck Dubosc ; Alexandra Lamy ; Elsa Zylberst...,14 mars 2018,Tout le monde debout,3.6,Franck Dubosc ;,4.3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Rooney Mara ; Joaquin Phoenix ; Chiwetel Ejiof...,28 mars 2018,Marie Madeleine,2.2,Garth Davis ;,3.2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Arnaud Ducret ; Louise Bourgoin ; Timéo Bollan...,28 mars 2018,"Les dents, pipi et au lit",2.6,Emmanuel Gillibert ;,3.6,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Cécile de France ;,28 mars 2018,Blue,3.6,Keith Scholey ; Alastair Fothergill ;,4.0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
df = df.drop('actors', axis=1)

In [10]:
df.head()

,date,movie,press_rating,producer,spectators_rating,'Rim'K' Brahmi-Benalla Abdelkrim,A. Martinez,A. Michael Baldwin,A.J.,A.J. Buckley,...,İnanç Konukçu,İnci Pars,İnci Türkay,İsmail Hacıoğlu,Şafak Sezer,Şahan Gökbakar,Şahika Tekand,Şebnem Bozoklu,Şener Şen,Şükrü Özyıldız
0,28 mars 2018,Ready Player One,4.2,Steven Spielberg ;,4.5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14 mars 2018,Tout le monde debout,3.6,Franck Dubosc ;,4.3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,28 mars 2018,Marie Madeleine,2.2,Garth Davis ;,3.2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,28 mars 2018,"Les dents, pipi et au lit",2.6,Emmanuel Gillibert ;,3.6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,28 mars 2018,Blue,3.6,Keith Scholey ; Alastair Fothergill ;,4.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
df = pd.concat([df, df['producer'].str.get_dummies(sep=" ; ")], axis=1)

In [12]:
df.head()

,date,movie,press_rating,producer,spectators_rating,'Rim'K' Brahmi-Benalla Abdelkrim,A. Martinez,A. Michael Baldwin,A.J.,A.J. Buckley,...,Étienne Chatiliez,Óskar Jónasson,Óskar Thór Axelsson,Ömer Faruk Sorak,Ömer Vargı,Özcan Deniz,Özgür Bakar,Özlem Akovalıgil,Şenol Sönmez,Şerif Gören
0,28 mars 2018,Ready Player One,4.2,Steven Spielberg ;,4.5,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14 mars 2018,Tout le monde debout,3.6,Franck Dubosc ;,4.3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,28 mars 2018,Marie Madeleine,2.2,Garth Davis ;,3.2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,28 mars 2018,"Les dents, pipi et au lit",2.6,Emmanuel Gillibert ;,3.6,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,28 mars 2018,Blue,3.6,Keith Scholey ; Alastair Fothergill ;,4.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
df = df.drop('producer', axis=1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25504 entries, 0 to 25503
Columns: 39722 entries, date to Şerif Gören
dtypes: float64(2), int64(39718), object(2)
memory usage: 7.5+ GB

In [15]:
df.to_csv('data_processing_3.csv')